[package]
name = "ActixWebSample"
version = "0.1.0"
authors = ["TUJINGWENDAO <847071279@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
env_logger = "0.7"

[dev-dependencies]
actix-rt = "1"
